# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-21 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171221_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='random', unique=True),
            preserve_default=False,
        ),
    ]
