# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-22 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20171222_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 12, 22, 15, 8, 35, 657000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
